package com.mitosis.aviate.util;

public final class Constants {
	public static final String E0001="E0001";
	public static final String E0002="E0002";
	public static final String E0003="E0003";
	public static final String E0004="E0004";
	public static final String E0005="E0005";
	public static final String E0006="E0006";
	public static final String E0007="E0007";
	public static final String E0008="E0008";
	public static final String E0009="E0009";
	public static final String E0010="E0010";
	public static final String E0011="E0011";
	public static final String E0012="E0012";
	public static final String E0013="E0013";
	public static final String E0014="E0014";
	public static final String E0015="E0015";
	public static final String E0016="E0016";
	public static final String E0017="E0017";
	public static final String E0001Error="Mandatory Fields missing, please provide values for mandatory fields";
	public static final String IntegrityError="User already exists";
	public static final String LOGINDENIED="Invalid Email/Password";
	public static final String E0004Error="Invalid account";
	public static final String E0005Error="Exception: ";
	public static final String E0006Error="Unable to save or update Address";
	public static final String E0007Error="Customer added product is already exist in list";
	public static final String E0008Error="There is no product in mylist";
	public static final String E0009Error="This category already exit";
	public static final String E0010Error="can not add entered category";
	public static final String E0011Error="This product type already exit";
	public static final String E0012Error="can not add entered subcategory";
	public static final String E0013Error="can not able to add parent category";
	public static final String E0014Error="unable to add or update product to my cart due to technical issue";
	public static final String E0015Error="unable to delete product from my cart";
	public static final String E0016Error="customer Id missing";
	public static final String E0017Error="This category already has product type";
	public static final String FAILURE="FAILURE";
	public static final String SUCCESS="SUCCESS";
	public static final String GOOGLE_SERVER_KEY = "AIzaSyBIy9JnsUNw-ZBhStC8os3mUkH-OpS1rF0";
	public static final String MESSAGE_KEY = "message";
	public static final String APNS_CERTIFICATE = "/apnscertificate/Deve_Certificates.p12";
	public static final String SSLKEY = "/sslkey/WS1909377130._.1.ks";
	public static final String APNS_KEY = "123456";
	public static final String AddressError = "Error while updating Address";
}
